name: afrika_baba
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  swipeable_button_view: ^0.0.2
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.26
  http: ^1.2.2
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  dio: ^5.7.0
  shimmer: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.4.1
  video_player: 2.5.0
  appinio_video_player: 1.2.0
  flutter_launcher_icons: ^0.14.0
  intl: ^0.19.0
  infinite_scroll_pagination: ^4.0.0
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Logo.png"
  remove_alpha_ios: true

flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - assets/groupe_icone_2/
    - assets/groupe_icone_1/
    - assets/Apple.png
    - assets/facebook.png
    - assets/gmail.png
    - assets/default.png
    - assets/no_connect.png
    - assets/Logo.png
